{% set name = "strct" %}
{% set version = "0.0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c46d38628e442de341601958bc3fb9d7fa2adba4131bdecdf76c20d7079fe885

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - strct

about:
  home: https://github.com/shaypal5/strct
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A small pure-python package for data strcture related utility functions.'

  description: |
    A small pure-python package for data strcture related utility functions.
  dev_url: https://github.com/shaypal5/strct

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
