{% set name = "strct" %}
{% set version = "0.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82ed6a7d4ab520f5eb1e75f059fb8eb1fb44cc2840e4ca97b48bd9080689c776

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - strct

about:
  home: https://github.com/shaypal5/strct
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A small pure-python package for data strcture related utility functions.'

  description: |
    A small pure-python package for data strcture related utility functions.
  dev_url: https://github.com/shaypal5/strct

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
